import { CategoryDataType, Campaign } from "@/types";

export const categoryData: CategoryDataType[] = [
  {
    id: "communities",
    name: "Community members",
    icon: "/svgs/community.svg",
  },
  {
    id: "creatives",
    name: "Creative Individuals",
    icon: "/svgs/idea.svg",
  },
  {
    id: "disaster",
    name: "Disaster Relief",
    icon: "/svgs/disaster.svg",
  },
  {
    id: "family",
    name: "Family support",
    icon: "/svgs/family.svg",
  },
  {
    id: "health",
    name: "Health support",
    icon: "/svgs/medical.svg",
  },
];

export const data: Campaign[] = [
  {
    amountCollected: 0,
    deadline: 1736776000,
    description: "Help fund a community garden project",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=1",
    owner: "0x91eE4Dd3a6E4dE54B3A2a5Bb394Ae5F3B6F92879",
    target: 50000,
    title: "Community Garden Project",
    _id: 1,
  },
  {
    amountCollected: 0,
    deadline: 1736876000,
    description: "Raise funds for school supplies for underprivileged children",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=2",
    owner: "0xBd1e99bF1Bc8Fb1247Db4e13e9F5Adb0cA5Df915",
    target: 20000,
    title: "School Supplies Drive",
    _id: 2,
  },
  {
    amountCollected: 0,
    deadline: 1736976000,
    description: "Funding for a local animal shelter",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=3",
    owner: "0x9CeDe5B6cE7c8E54aFcB6BdDf7F8A5D91c5eF7a1",
    target: 80000,
    title: "Animal Shelter Support",
    _id: 3,
  },
  {
    amountCollected: 0,
    deadline: 1737076000,
    description: "Crowdfunding for a startup tech company",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=4",
    owner: "0xD12e6e6B1bF3De6E4D5E7F8Ae4B1D1b5A1F91E9a",
    target: 100000,
    title: "Tech Startup Funding",
    _id: 4,
  },
  {
    amountCollected: 0,
    deadline: 1737176000,
    description: "Support for a community healthcare initiative",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=5",
    owner: "0xE3D1F6C4E2F8B1D9F5C1Ae4b7F9D91B4A1B7C5aE",
    target: 75000,
    title: "Healthcare Initiative",
    _id: 5,
  },
  {
    amountCollected: 0,
    deadline: 1737276000,
    description: "Raise funds for a clean water project in rural areas",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=6",
    owner: "0xB2C3D4E5F6A1B7C8E5D4E7F8Ae6B1D9F5C1Ae4b7",
    target: 60000,
    title: "Clean Water Project",
    _id: 6,
  },
  {
    amountCollected: 0,
    deadline: 1737376000,
    description: "Funding for renewable energy research",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=7",
    owner: "0xC5D4E7F8B1D9F5C1Ae4B7F9D91B4A1B7C5aE6D1F",
    target: 90000,
    title: "Renewable Energy Research",
    _id: 7,
  },
  {
    amountCollected: 0,
    deadline: 1737476000,
    description: "Help fund an artist's new exhibition",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=8",
    owner: "0xD5C1Ae4b7F9D91B4A1B7C5aE6D1F2E3B4A1B7C5a",
    target: 45000,
    title: "Art Exhibition Funding",
    _id: 8,
  },
  {
    amountCollected: 0,
    deadline: 1737576000,
    description: "Support for a local food bank initiative",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=9",
    owner: "0xE6D1F2E3B4A1B7C5aD5C1Ae4b7F9D91B4A1B7C5a",
    target: 30000,
    title: "Food Bank Initiative",
    _id: 9,
  },
  {
    amountCollected: 0,
    deadline: 1737676000,
    description:
      "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Minima tenetur nulla corporis quaerat illo aut, excepturi fuga exercitationem, quas mollitia magnam. Alias at consequuntur dolore adipisci maxime saepe debitis hic.Voluptates modi, culpa atque possimus rerum ipsum dignissimos cumque distinctio, laborum odio voluptatum eum. Fugiat eligendi tempora delectus ratione, vel eaque quidem itaque rerum quas deleniti dolores quae, inventore harum?Illo impedit illum soluta exercitationem nemo est totam accusantium corrupti consequatur fugit ipsa, iure, atque tempora ex sunt natus? Corrupti veniam provident veritatis dolorem commodi, velit nam enim similique architecto?Iure eum necessitatibus inventore voluptates ab aliquam fugit, qui dignissimos rem repellat maiores cupiditate perspiciatis repudiandae doloremque. Velit totam assumenda eligendi? Sunt placeat quidem molestias nesciunt eius quam maxime vitae.Minus nobis placeat quae architecto. Facilis blanditiis culpa fugiat exercitationem impedit! Provident veritatis illo asperiores ullam! Facilis tempore quasi, deleniti, obcaecati fugit esse soluta ratione ab magni officiis quis quibusdam!Enim voluptates maiores natus velit. Molestiae molestias odio suscipit. Laudantium amet neque optio esse hic, laborum nemo quia eligendi laboriosam sed eius impedit accusantium alias harum tenetur nisi. Molestias, sunt?Facilis excepturi mollitia consectetur nesciunt in voluptatibus veniam quaerat libero commodi eligendi ",
    donations: [],
    donators: [],
    image:
      "https://www.becomingminimalist.com/wp-content/uploads/2022/05/help-others.jpg",
    owner: "0xF6A1B7C5aD5C1Ae4b7F9D91B4A1B7C5aE6D1F2E3",
    target: 70000,
    title: "Community Sports Center",
    _id: 10,
  },
  {
    amountCollected: 0,
    deadline: 1737776000,
    description: "Raise funds for disaster relief efforts",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=11",
    owner: "0xB4A1B7C5aD5C1Ae4b7F9D91B4A1B7C5aE6D1F2E3",
    target: 85000,
    title: "Disaster Relief Fund",
    _id: 11,
  },
  {
    amountCollected: 0,
    deadline: 1737876000,
    description: "Funding for a community literacy program",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=12",
    owner: "0xE3B4A1B7C5aD5C1Ae4b7F9D91B4A1B7C5aE6D1F2",
    target: 40000,
    title: "Literacy Program Support",
    _id: 12,
  },
  {
    amountCollected: 0,
    deadline: 1737976000,
    description: "Help fund a sustainable farming project",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=13",
    owner: "0xF2E3B4A1B7C5aD5C1Ae4b7F9D91B4A1B7C5aE6D1",
    target: 55000,
    title: "Sustainable Farming Project",
    _id: 13,
  },
  {
    amountCollected: 0,
    deadline: 1738076000,
    description: "Raise funds for a tech education initiative",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=14",
    owner: "0xD1F2E3B4A1B7C5aD5C1Ae4b7F9D91B4A1B7C5aE6",
    target: 65000,
    title: "Tech Education Initiative",
    _id: 14,
  },
  {
    amountCollected: 0,
    deadline: 1738176000,
    description: "Support for a local theater company",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=15",
    owner: "0xC5aE6D1F2E3B4A1B7C5aD5C1Ae4b7F9D91B4A1B7",
    target: 35000,
    title: "Theater Company Support",
    _id: 15,
  },
  {
    amountCollected: 0,
    deadline: 1738276000,
    description: "Help fund a music education program for youth",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=16",
    owner: "0xE6D1F2E3B4A1B7C5aD5C1Ae4b7F9D91B4A1B7C5a",
    target: 48000,
    title: "Music Education Program",
    _id: 16,
  },
  {
    amountCollected: 0,
    deadline: 1738376000,
    description: "Crowdfunding for a small business startup",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=17",
    owner: "0xB7C5aD5C1Ae4b7F9D91B4A1B7C5aE6D1F2E3B4A1",
    target: 90000,
    title: "Small Business Startup",
    _id: 17,
  },
  {
    amountCollected: 0,
    deadline: 1738476000,
    description: "Funding for a community fitness center",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=18",
    owner: "0xD5C1Ae4b7F9D91B4A1B7C5aE6D1F2E3B4A1B7C5",
    target: 70000,
    title: "Community Fitness Center",
    _id: 18,
  },
  {
    amountCollected: 0,
    deadline: 1738576000,
    description: "Help fund a wildlife conservation project",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=19",
    owner: "0xE3B4A1B7C5aD5C1Ae4b7F9D91B4A1B7C5aE6D1F2",
    target: 85000,
    title: "Wildlife Conservation Project",
    _id: 19,
  },
  {
    amountCollected: 0,
    deadline: 1738676000,
    description: "Raise funds for a local library renovation",
    donations: [],
    donators: [],
    image: "https://source.unsplash.com/random/800x600?sig=20",
    owner: "0xF2E3B4A1B7C5aD5C1Ae4b7F9D91B4A1B7C5aE6D1",
    target: 64000,
    title: "Library Renovation Project",
    _id: 20,
  },
];
